#!/usr/bin/env bash

brew update
brew upgrade
brew cleanup
brew prune
brew doctor

echo

brew cask cleanup
brew cask doctor

echo

# pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
# pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3 install -U

# bash

